#!/bin/bash
set -eux

if [ -x autogen.sh ]; then
    ./autogen.sh
else
    autoreconf -fvi
fi

ROOT=$HOME/.cache/w32/
mkdir -p $ROOT

export PKG_CONFIG_PATH=$ROOT/lib/pkgconfig
./configure \
    --host=i686-w64-mingw32 \
    --prefix=$ROOT \
    --exec-prefix=$ROOT \
    LDFLAGS=-L$ROOT/lib/ \
    "$@"
make -j 12 INCLUDES=-I$ROOT/include/
make install
our_oldpwd=$(pwd)
cd ..
rm -rf $our_oldpwd

